### ISSUE TITLE
Issue with batched queries 

### ISSUE THREAD

**Issue by emanuelet** [nearform/mercurius-apollo-tracing#125]
I don't know if it was a known issue, but the package has issue with tracing batched queries.

From our investigation, the queries will land on the hooks already splitted but they share the same context, which will throw an error like so.

```
Error: [internal mercurius error] stopTiming called twice!
[GQL]               at internalError (/Users/jp/Development/backend/mercurius-apollo-tracing/src/ApolloTraceBuilder.js:9:12)
[GQL]               at ApolloTraceBuilder.stopTiming (/Users/jp/Development/backend/mercurius-apollo-tracing/src/ApolloTraceBuilder.js:47:19)
[GQL]               at /Users/jp/Development/backend/mercurius-apollo-tracing/src/index.js:43:22
[GQL]               at onResolutionHookRunner (/Users/jp/Development/backend/node_modules/mercurius/lib/hooks.js:148:10)
[GQL]               at hooksRunner (/Users/jp/Development/backend/node_modules/mercurius/lib/hooks.js:84:11)
[GQL]               at onResolutionHandler (/Users/jp/Development/backend/node_modules/mercurius/lib/handlers.js:67:9)
[GQL]               at maybeFormatErrors (/Users/jp/Development/backend/node_modules/mercurius/index.js:677:13)
[GQL]               at Object.fastifyGraphQl [as graphql] (/Users/jp/Development/backend/node_modules/mercurius/index.js:659:12)
[GQL]               at processTicksAndRejections (node:internal/process/task_queues:96:5)
[GQL]               at async Promise.all (index 0)
```

**Comment by drakhart** [comment]
I've been looking into solving this, but haven't been able to.

Here's some overview:
- mercurius-apollo-tracing relies on Mercurius' lifecycle hooks to [start/stop the tracing timer](https://github.com/drakhart/mercurius-apollo-tracing/blob/main/src/index.ts#L67) and [extract query data](https://github.com/drakhart/mercurius-apollo-tracing/blob/main/src/hookIntoSchemaResolvers.ts).
- [It injects the tracer into the context object](https://github.com/drakhart/mercurius-apollo-tracing/blob/main/src/index.ts#L69), which is shared across all the operation definitions in a batch of queries (there's no individual context for each operation).
- When the second operation of a batched query resolves, [the only existing tracer](https://github.com/drakhart/mercurius-apollo-tracing/blob/main/src/index.ts#L83) receives a second ["stop timer" order](https://github.com/drakhart/mercurius-apollo-tracing/blob/main/src/index.ts#L93) which obviously fails.

As a solution, I thought of creating multiple tracers, one for each individual operation, injecting all of them into the context and then retrieving them as needed through the lifecycle of the operation, but there are two major pain points for doing the latter:
1. The `context.__currentQuery` value is not updated anymore after [the query execution](https://github.com/mercurius-js/mercurius/blob/ef154c50b3efc3f68a2c95269ebb277f379d1a12/lib/routes.js#L228), hence it can't be used to retrieve the specific tracer at the `onResolution` hook.
2. Instead of `context.__currentQuery` we could use the `document` object, but [the `onResolution` hook simply lacks it (it only has the resolution and, again, the context).](https://github.com/mercurius-js/mercurius/blob/0cc41fbeb529954425b94a5c79e08347f51747a8/examples/hooks-gateway.js#L215). The field resolver used by the [hookIntoSchemaResolvers](https://github.com/drakhart/mercurius-apollo-tracing/blob/main/src/hookIntoSchemaResolvers.ts) function also lacks this `document` object, though it has an `info` object that MAYBE could be used for the same purpose.

I believe that this won't be fixed until Mercurius solves those two pain points, since I can't see any other way for mercurius-apollo-tracing to identify individual operation definitions in a batch of queries without those. And honestly, I don't believe that solving this issue is enough justification to undertake all that work in Mercurius.

**Comment by drakhart** [comment]
I'm reopening this issue since there's a new possibility of fixing it after https://github.com/mercurius-js/mercurius/issues/842 has been resolved.

**Comment by drakhart** [comment]
Looks like https://github.com/mercurius-js/mercurius/issues/842 wasn't finally fixed, I've opened https://github.com/mercurius-js/mercurius/issues/858 to continue working on it.
