### ISSUE TITLE
Add support for client awareness

### ISSUE THREAD

**Issue by juusopiikkila** [nearform/mercurius-apollo-tracing#209]
Apollo tracing has a feature where you can differentiate clients with name and version with headers `apollographql-client-name` and `apollographql-client-version`. This plugin doesn't seem to catch these headers and report them to Apollo Studio.

More documentation here: https://www.apollographql.com/docs/graphos/metrics/client-awareness/

**Comment by andysm1th** [comment]
This project is built on top of version 3 of the `apollo-server-core` and `apollo-reporting-protobuf` dependencies

These were deprecated back in October last year.

Rather than build upon something with deprecated APIs this implementation should either be reworked or potentially archived before any additional work is introduced.
